### PR TITLE
Pass through whether we are scanning coinbase transactions or not

### PR DESCRIPTION
**Pull request by brandonlehmann**

### CODE REVIEW

**Comment by zpalmtree** [comment]
Not passing tests

**Comment by brandonlehmann** [comment]
> Not passing tests

Fix your incorrect assumptions regarding what blocks are returned :)

**Comment by zpalmtree** [comment]
> > Not passing tests
> 
> Fix your incorrect assumptions regarding what blocks are returned :)

You're the one making the PR :)

**Comment by brandonlehmann** [comment]
Not anymore

**Pull request closed without merging**
