### PR TITLE
Add syncing with /getrawblocks

### PR DESCRIPTION
**Pull request by The-Cat-In-The-Hat**
This needs the development branch of turtlecoin-utils and this patch https://github.com/turtlecoin/turtlecoin-utils/pull/30 to compile and work

also fixes this issue https://github.com/turtlecoin/turtlecoin-wallet-backend-js/issues/54

### CODE REVIEW

**Comment by zpalmtree** [comment]
Thanks for the PR. Will review once the threaded-rpc branch is merged.

**Comment by zpalmtree** [comment]
I see threaded-rpc has been merged now. I will try and get round to reviewing ASAP. Can you fix the merge conflicts?

**Comment by RocksteadyTC** [comment]
What are we doing here?

**Comment by zpalmtree** [comment]
Kind of waiting on https://github.com/turtlecoin/turtlecoin-utils/pull/30 but ibmcd is adding typings himself I believe by rewriting it in typescript.. so I think that PR will get closed

**Comment by brandonlehmann** [comment]
Correct. Working my way up the stack now :) starting with crypto

**Comment by RocksteadyTC** [comment]
Thanks

**Comment by zpalmtree** [comment]
Rebased and merged in #85

**Pull request closed without merging**
