### PR TITLE
Unit tests for ValidateParameters

### PR DESCRIPTION
**Pull request by ivantse**
I felt a bit uneasy with my documentation in https://github.com/turtlecoin/turtlecoin-wallet-backend-js/pull/99 without actually running the code to make sure it worked. Here, I've added unit tests for `ValidateParameters` to make sure that what I had documented is correct.

Open to suggestions if there are better ways to structure/name things than what I've done here.

Furthermore:
* moving `Tester` and `TestStatus` to its own module so it can be used in unit tests
* running `ValidateParametersTests` after other tests

### CODE REVIEW

**Comment by zpalmtree** [comment]
Changes look pretty good, though I would prefer a different name for `ValidateParameters.tests.ts`, maybe `ValidateParametersTests.ts`?

It also would be good to have a test that verifies the `isIntegratedAddress` parameter functions as expected - a valid integrated address should be marked as invalid, unless this parameter is set to `true`.

Currently, the `tests.ts` file contains tests for more than just the `WalletBackend` class, it has a few tests for things like `generateKeyDerivation` and their performance (which aren't really helpful, to be honest), or the ledger tests, which could potentially be moved into their own files, as well.

Also, the indentation on `tests/lib/ValidateParameters.tests.ts` is wrong, it should be 4 space indents. There should be a pre-commit hook which auto formats the code, but that might not be working in your editor - you can manually run `yarn style`, and I've updated github actions to include the linter output in the pre merge checks.

**Comment by ivantse** [comment]
Awesome, thanks for the feedback!

1. Will rename to `ValidateParametersTests.ts` 👍 
1. I'll add a test that verified usage of the `integratedAddressesAllowed` parameter
1. Thanks for clarifying about the tests in `tests.ts`; I can take a stab at pulling out pieces of it in another PR
1. I don't think our `.eslintrc` is enforcing 4 spaces right now. A local run of `yarn style` doesn't yield any errors in this branch. Should we add this rule: `'indent': ['error', 4]` ?

**Comment by zpalmtree** [comment]
>     4. I don't think our `.eslintrc` is enforcing 4 spaces right now. A local run of `yarn style` doesn't yield any errors in this branch. Should we add this rule: `'indent': ['error', 4]` ?
Ah, my bad. That would be great.

**Comment by ivantse** [comment]
* eslintrc updates addressed in #101 
* added tests for handling integrated addresses

**Comment by zpalmtree** [comment]
Looks good, thank you!

**Pull request merged**
