### PR TITLE
fix wrong path to package.json

### PR DESCRIPTION
**Pull request by ExtraHash**
In the compiled module, the directory structure is as follows:

```
.
package.json
├── dist
│   └── lib
└── node_modules
    ├── lodash
    │   └── fp
    └── typescript
        ├── bin
        └── lib
```

### CODE REVIEW

**Comment by zpalmtree** [comment]
The `package.json` is *meant* to be in `dist/` - not `/` - this is the root package.json, rather than the one we copied in. I was under the impression that npm was just publishing the compiled files that I specified in the `files` field.
However, upon re-reading the documentation, I see that `package.json` is always included, so a relative require *should* always work..

**Comment by ExtraHash** [comment]
there is no package.json in the dist folder.

**Comment by zpalmtree** [comment]
I think this is because I forgot to include it in the npm publish, which is easily fixable, but we don't need the scripts and other hackery if we can just use the root one.

**Comment by ExtraHash** [comment]
I don't see any reason *not* to use the root one, I've done a similar thing in my wallet in order to not have to manually bump the version number all over the place.

**Pull request merged**
