### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by brandonlehmann**
* Committing `/dist` is a sin punishable by death
* Updated typedoc dependency to try to resolve the security vulnerability in [marked](https://www.npmjs.com/advisories/812)
* Resolved a typing issue in `BlockchainCacheApi.ts`

### CODE REVIEW

**Comment by zpalmtree** [comment]
Can you confirm that all the necessary files will get committed to npm with these changes

**Comment by brandonlehmann** [comment]
I’ll take another look; however, a npm install does build the dist files and thus installing from npm should do the same. I’ll try and report back.

**Comment by zpalmtree** [comment]
Bump

**Comment by zpalmtree** [comment]
Implemented in 3.2.0

**Pull request closed without merging**
